### ISSUE TITLE
Constraint on atac_queue out of sync with stored procedure

### ISSUE THREAD

**Issue by maurits-h** [sqlTopia/sp_AlterColumn#4]
It seems constraint `ck_atac_queue_action_code_sort_order_phase` as defined in `atac.queue.sql` was not updated along with changes made to the stored procedure. Many action codes have a different sort order in the stored procedure than the constraint will allow, and many codes listed in the constraint are not even present in the stored procedure.

**Comment by maurits-h** [comment]
And I'm wondering if the constraint will even work as intended, because the ANDs are not in parentheses and so they will mix with the ORs:

```
   action_code = 'didt' AND sort_order =   0 AND phase = 0
OR action_code = 'drdt' AND sort_order =  10 AND phase = 0

OR action_code = 'ditg' AND sort_order =  20 AND phase = 1
OR action_code = 'drtg' AND sort_order =  30 AND phase = 1

OR action_code = 'difk' AND sort_order =  40 AND phase = 2
OR action_code = 'drfk' AND sort_order =  50 AND phase = 2
```

Should this not be:

```
   (action_code = 'didt' AND sort_order =   0 AND phase = 0)
OR (action_code = 'drdt' AND sort_order =  10 AND phase = 0)

OR (action_code = 'ditg' AND sort_order =  20 AND phase = 1)
OR (action_code = 'drtg' AND sort_order =  30 AND phase = 1)

OR (action_code = 'difk' AND sort_order =  40 AND phase = 2)
OR (action_code = 'drfk' AND sort_order =  50 AND phase = 2)
```

**Comment by swePeso** [comment]
No, as AND has higher priority than OR.

 

https://learn.microsoft.com/en-us/sql/t-sql/language-elements/operator-precedence-transact-sql?view=sql-server-ver16

**Comment by swePeso** [comment]
I will have a look!

Thank you.

 

 

//Peter

 

 

From: maurits-h ***@***.***> 
Sent: Tuesday, 28 March 2023 17:06
To: sqlTopia/sp_AlterColumn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sqlTopia/sp_AlterColumn] Constraint on atac_queue out of sync with stored procedure (Issue #4)

 

It seems constraint ck_atac_queue_action_code_sort_order_phase as defined in atac.queue.sql was not updated along with changes made to the stored procedure. Many action codes have a different sort order in the stored procedure than the contstraint will allow, and many codes listed in the constraint are not even present in the stored procedure.

**Comment by swePeso** [comment]
Procedure and table should be in sync now,

 

 

//Peter

 

 

From: maurits-h ***@***.***> 
Sent: Tuesday, 28 March 2023 17:06
To: sqlTopia/sp_AlterColumn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sqlTopia/sp_AlterColumn] Constraint on atac_queue out of sync with stored procedure (Issue #4)

 

It seems constraint ck_atac_queue_action_code_sort_order_phase as defined in atac.queue.sql was not updated along with changes made to the stored procedure. Many action codes have a different sort order in the stored procedure than the contstraint will allow, and many codes listed in the constraint are not even present in the stored procedure.

**Comment by maurits-h** [comment]
> No, as AND has higher priority than OR.

Wow. I never knew this, thank you. I don't think I'll ever write it like this though :-)

> Procedure and table should be in sync now

Thank you for your quick response!
